# Generated by Django 2.2.1 on 2019-05-10 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=50)),
                ('middlename', models.CharField(blank=True, max_length=50, null=True)),
                ('birthday', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unspecified', 'Unspecified')], max_length=50)),
                ('edu_qualification', models.CharField(choices=[('O Level', 'O Level'), ('Undergraduate', 'Undergraduate'), ('OND/HND', 'OND/HND'), ("Bachelor's Degree", "Bachelor's Degree"), ("Master's Degree", "Master's Degree"), ('Other', 'Other')], max_length=50)),
                ('program', models.CharField(choices=[('Codegaminators', (('Codegaminators - Animation', 'Animation'), ('Codegaminators - Coding', 'Coding'), ('Codegaminators - Database', 'Database'), ('Codegaminators - Game Development', 'Game Development'), ('Codegaminators - Hardware/Networking', 'Hardware/Networking'), ('Codegaminators - Photography', 'Photography'))), ('ICT and Digital Lifestyle', (('ICT and Digi-Lifestyle 5:00pm', 'ICT and Digital Lifestyle - 5:00pm'), ('ICT and Digi-Lifestyle 6:30pm', 'ICT and Digital Lifestyle - 6:30pm'))), ('Digi-lifestyle for kids', (('Digi-lifestyle for kids 9:00am', 'Digi-lifestyle for kids - 9:00am'), ('Digi-lifestyle for kids 1:00pm', 'Digi-lifestyle for kids - 1:00pm'))), ('DBA 500', (('DBA 500', 'DBA 500'),))], max_length=50)),
                ('state_of_origin', models.CharField(max_length=50)),
                ('local_govt', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('unique_id', models.CharField(max_length=15, unique=True)),
                ('roll_no', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('date', models.DateField(auto_now_add=True)),
                ('present', models.BooleanField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('linked_student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance', to='attendance.Student')),
            ],
            options={
                'verbose_name_plural': 'Attendance',
                'ordering': ['linked_student'],
            },
        ),
    ]
