# Generated by Django 2.2.1 on 2019-05-16 12:17

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='birthday',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='student',
            name='edu_qualification',
            field=models.CharField(choices=[('O Level', 'O Level'), ('Undergraduate', 'Undergraduate'), ('OND/HND', 'OND/HND'), ("Bachelor's Degree", "Bachelor's Degree"), ("Master's Degree", "Master's Degree"), ('Other', 'Other')], max_length=50, verbose_name='Educational Qualification'),
        ),
        migrations.AlterField(
            model_name='student',
            name='local_govt',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='state', chained_model_field='state', on_delete=django.db.models.deletion.CASCADE, to='attendance.State'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_no',
            field=models.CharField(max_length=15, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Number of times present'),
        ),
        migrations.AlterField(
            model_name='student',
            name='state_of_origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_s', to='attendance.State'),
        ),
        migrations.CreateModel(
            name='Local_govt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='local_government', to='attendance.State')),
            ],
        ),
    ]
