# Generated by Django 2.2.1 on 2019-05-16 13:33

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_auto_20190516_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='local_govt',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='state_of_origin', chained_model_field='state', on_delete=django.db.models.deletion.CASCADE, to='attendance.Local_govt', verbose_name='Local Government'),
        ),
        migrations.AlterField(
            model_name='student',
            name='state_of_origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student', to='attendance.State'),
        ),
        migrations.AlterField(
            model_name='student',
            name='unique_id',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
