# Generated by Django 2.2.1 on 2019-05-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_auto_20190523_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='already_taken',
            field=models.BooleanField(default=False),
        ),
    ]
