# Generated by Django 2.2.1 on 2019-05-23 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_auto_20190523_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='linked_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance', to='attendance.Student'),
        ),
    ]
