# Generated by Django 2.2.1 on 2019-05-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_auto_20190523_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='present_state',
            field=models.BooleanField(default=False),
        ),
    ]
