# Generated by Django 2.2.1 on 2019-05-27 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_attendance_present_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['date', 'linked_student'], 'verbose_name_plural': 'Attendance'},
        ),
        migrations.AlterField(
            model_name='attendance',
            name='linked_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance', to='attendance.Student', unique_for_date='date'),
        ),
    ]
