# Generated by Django 2.2.1 on 2019-06-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0019_auto_20190613_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='program_version',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Program Version'),
        ),
        migrations.AlterField(
            model_name='student',
            name='state_of_origin',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='State of Origin'),
        ),
    ]
