# Generated by Django 2.2.1 on 2019-06-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0020_auto_20190617_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='program_specific',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sub Program'),
        ),
    ]
