# Generated by Django 2.2.1 on 2019-07-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0021_student_program_specific'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='picture',
            field=models.ImageField(default='/static/images/icons8-customer-64.png', upload_to='media/'),
        ),
    ]
