# Generated by Django 2.2.1 on 2019-07-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0022_auto_20190703_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='already_taken',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
