# Generated by Django 2.2.1 on 2019-07-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0023_auto_20190703_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='already_taken',
            field=models.BooleanField(default=False),
        ),
    ]
