# Generated by Django 2.2.1 on 2019-07-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0027_auto_20190712_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='edu_qualification',
            field=models.CharField(blank=True, choices=[('O Level', 'O Level'), ('Undergraduate', 'Undergraduate'), ('OND/HND', 'OND/HND'), ("Bachelor's Degree", "Bachelor's Degree"), ("Master's Degree", "Master's Degree"), ('Other', 'Other')], max_length=50, null=True, verbose_name='Educational Qualification'),
        ),
    ]
